services:
  db:
    image: postgres:18
    container_name: customer-events-db
    environment:
      POSTGRES_DB: events
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change-me}
    ports:
      - "5433:5432"
  
  app:
    build: .
    container_name: customer-events-app
    env_file:
      - ./cmd/server/.env
    ports:
      - "8080:8080"
    depends_on:
      - db